// <auto-generated />
using System;
using FitCore.Workouts.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FitCore.Workouts.Infrastructure.Migrations
{
    [DbContext(typeof(WorkoutsDbContext))]
    [Migration("20261008150000_AgregarPesoYProgresos")]
    partial class AgregarPesoYProgresos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FitCore.Workouts.Domain.Entidades.Ejercicio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DescripcionOrientativa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GrupoMuscular")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Ejercicios", (string)null);
                });

            modelBuilder.Entity("FitCore.Workouts.Domain.Entidades.ProgresoEjercicio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EjercicioId")
                        .HasColumnType("uuid");

                    b.Property<bool>("EsRecordPersonal")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreEjercicio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PesoAnteriorKg")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<decimal>("PesoNuevoKg")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<int>("RepeticionesAnteriores")
                        .HasColumnType("integer");

                    b.Property<int>("RepeticionesNuevas")
                        .HasColumnType("integer");

                    b.Property<Guid>("RutinaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "EjercicioId");

                    b.ToTable("ProgresosEjercicio", (string)null);
                });

            modelBuilder.Entity("FitCore.Workouts.Domain.Entidades.Rutina", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreadorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NivelDificultad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("PermitirEdicionEntrenador")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Rutinas", (string)null);
                });

            modelBuilder.Entity("FitCore.Workouts.Domain.Entidades.RutinaEjercicio", b =>
                {
                    b.Property<Guid>("RutinaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EjercicioId")
                        .HasColumnType("uuid");

                    b.Property<int>("OrdenAparicion")
                        .HasColumnType("integer");

                    b.Property<decimal>("PesoKg")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<int>("Repeticiones")
                        .HasColumnType("integer");

                    b.Property<int>("Series")
                        .HasColumnType("integer");

                    b.Property<int>("TiempoDescansoSegundos")
                        .HasColumnType("integer");

                    b.HasKey("RutinaId", "EjercicioId");

                    b.HasIndex("EjercicioId");

                    b.ToTable("RutinaEjercicios", (string)null);
                });

            modelBuilder.Entity("FitCore.Workouts.Domain.Entidades.RutinaEjercicio", b =>
                {
                    b.HasOne("FitCore.Workouts.Domain.Entidades.Ejercicio", "Ejercicio")
                        .WithMany("RutinaEjercicios")
                        .HasForeignKey("EjercicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitCore.Workouts.Domain.Entidades.Rutina", "Rutina")
                        .WithMany("RutinaEjercicios")
                        .HasForeignKey("RutinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ejercicio");

                    b.Navigation("Rutina");
                });

            modelBuilder.Entity("FitCore.Workouts.Domain.Entidades.Ejercicio", b =>
                {
                    b.Navigation("RutinaEjercicios");
                });

            modelBuilder.Entity("FitCore.Workouts.Domain.Entidades.Rutina", b =>
                {
                    b.Navigation("RutinaEjercicios");
                });
#pragma warning restore 612, 618
        }
    }
}
