version: '3.8'
services:
  postgres_db:
    image: postgres:15-alpine
    container_name: fitcore_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?Define POSTGRES_PASSWORD en .env}
      POSTGRES_DB: fitcore_identity
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgres_workouts:
    image: postgres:15-alpine
    container_name: fitcore_postgres_workouts
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?Define POSTGRES_PASSWORD en .env}
      POSTGRES_DB: fitcore_workouts
    ports:
      - "5433:5432"
    volumes:
      - postgres_workouts_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: fitcore_rabbitmq
    ports:
      - "5672:5672" # Puerto de comunicación
      - "15672:15672" # Panel web administrativo
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:?Define RABBITMQ_PASSWORD en .env}

volumes:
  postgres_data:
  postgres_workouts_data: