version: '3.8'
services:
  postgres_db:
    image: postgres:15-alpine
    container_name: fitcore_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: fitcore_rabbitmq
    ports:
      - "5672:5672" # Puerto de comunicación
      - "15672:15672" # Panel web administrativo
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  postgres_data: